## Compare Preprocessing Results with [Kernel](https://www.kaggle.com/sudalairajkumar/when-less-is-more) with RAM-Limited Data

In [1]:
import os
if os.name=='nt':
    try:
        mingw_path = 'C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin'
        os.environ['PATH'] = mingw_path + ';' + os.environ['PATH']
    except:
        pass
    
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import tqdm
import gc
import xgboost as xgb
from sklearn.preprocessing import LabelEncoder

tqdm.tqdm.pandas()

%matplotlib inline

In [2]:
cat_cols = ['ncodpers',
 'canal_entrada',
 'conyuemp',
 'ind_actividad_cliente',
 'ind_empleado',
 'ind_nuevo',
 'indext',
 'indfall',
 'indrel',
 'indrel_1mes',
 'indresi',
 'pais_residencia',
 'segmento',
 'sexo',
 'tipodom',
 'tiprel_1mes',
 'age',
 'antiguedad',
 'renta']

target_cols = ['ind_cco_fin_ult1',
 'ind_cder_fin_ult1',
 'ind_cno_fin_ult1',
 'ind_ctju_fin_ult1',
 'ind_ctma_fin_ult1',
 'ind_ctop_fin_ult1',
 'ind_ctpp_fin_ult1',
 'ind_deco_fin_ult1',
 'ind_dela_fin_ult1',
 'ind_deme_fin_ult1',
 'ind_ecue_fin_ult1',
 'ind_fond_fin_ult1',
 'ind_hip_fin_ult1',
 'ind_nom_pens_ult1',
 'ind_nomina_ult1',
 'ind_plan_fin_ult1',
 'ind_pres_fin_ult1',
 'ind_reca_fin_ult1',
 'ind_recibo_ult1',
 'ind_tjcr_fin_ult1',
 'ind_valo_fin_ult1',
 'ind_viv_fin_ult1']

## 2015-05-28 and 2015-06-28

In [3]:
train1 = pd.read_hdf('../input/data_month_2015-05-28.hdf', 'data_month')
train2 = pd.read_hdf('../input/data_month_2015-06-28.hdf', 'data_month')

# products in 2015-06-28
target = train2.loc[:, ['ncodpers']+target_cols].copy()
target.set_index('ncodpers', inplace=True, drop=False)
# a dataframe containing the ncodpers only
target_ncodpers = pd.DataFrame(target.ncodpers)
# drop ncodpers from target
target.drop('ncodpers', axis=1, inplace=True)

# products in 2015-05-28
prev_target = train1.loc[:, ['ncodpers']+target_cols].copy()
prev_target.set_index('ncodpers', inplace=True, drop=True)
# join to target_ncodpers, so that prev_target includes all customers in 2015-05-28
prev_target = target_ncodpers.join(prev_target, how='left')
prev_target.fillna(0.0, inplace=True)
prev_target.drop('ncodpers', axis=1, inplace=True)

# new products in 2015-06-28
target = target.subtract(prev_target)
target[target<0] = 0

# train set of 2015-06-28 includes customer features and products in 2015-05-28
x_vars = train2[cat_cols].copy()
x_vars.reset_index(inplace=True, drop=True)
x_vars.reset_index(inplace=True, drop=False)
x_vars_cols = x_vars.columns.tolist()
x_vars_cols[0] = 'sample_order'
x_vars.columns = x_vars_cols
x_vars.set_index('ncodpers', drop=True, inplace=True)
x_vars = x_vars.join(prev_target)

# get samples for each new product

# join target to x_vars
x_vars_new = x_vars.join(target, rsuffix='_t')

# set ncodpers as one column
x_vars_new.reset_index(inplace=True)
x_vars.reset_index(inplace=True)

# melt
x_vars_new = x_vars_new.melt(id_vars=x_vars.columns)
# mapping from target_cols to index
target_cols_mapping = {c+'_t': n for (n, c) in enumerate(target_cols)}
# replace column name by index
x_vars_new.variable.replace(target_cols_mapping, inplace=True)
# reorder rows
x_vars_new.sort_values(['sample_order', 'variable'], inplace=True)
# keep new products
x_vars_new = x_vars_new[x_vars_new.value>0]
# drop value
x_vars_new.drop(['sample_order', 'value'], inplace=True, axis=1)
# keep the order of samples as in the original data set
x_vars_new.reset_index(drop=True, inplace=True)

# variables
x_vars = x_vars_new.iloc[:, :-1].copy()
# target
target = x_vars_new.iloc[:, [0, -1]].copy()

## 2016-05-28 and 2016-06-28

In [5]:
train1 = pd.read_hdf('../input/data_month_2016-05-28.hdf', 'data_month')
train2 = pd.read_hdf('../input/data_month_2016-06-28.hdf', 'data_month')

# customer id in 2016-06-28
target_ncodpers = train2.loc[:, ['ncodpers']].copy()
target_ncodpers.set_index('ncodpers', inplace=True, drop=False)

# products in 2016-05-28
prev_target = train1.loc[:, ['ncodpers']+target_cols].copy()
prev_target.set_index('ncodpers', inplace=True, drop=True)

# join prev_target to target_ncodpers
prev_target = target_ncodpers.join(prev_target, how='left')
prev_target.fillna(0.0, inplace=True)
prev_target.drop('ncodpers', axis=1, inplace=True)

# train set of 2016-06-28 includes customer features and products in 2016-05-28
x_vars_test = train2[cat_cols].copy()
x_vars_test.set_index('ncodpers', drop=False, inplace=True)
x_vars_test = x_vars_test.join(prev_target)

In [44]:
train1 = pd.read_hdf('../input/data_month_2016-05-28.hdf', 'data_month')
train2 = pd.read_hdf('../input/data_month_2016-06-28.hdf', 'data_month')

In [49]:
target_ncodpers = train2.loc[:, ['ncodpers']].copy()
target_ncodpers.set_index('ncodpers', inplace=True, drop=False)

In [50]:
target_ncodpers

          ncodpers
ncodpers
15889        15889
1170544    1170544
1170545    1170545
1170547    1170547
1170548    1170548
1170550    1170550
1170552    1170552
1170553    1170553
1170555    1170555
1170557    1170557
1170559    1170559
1170563    1170563
1170542    1170542
1170565    1170565
1170568    1170568
1170570    1170570
1170576    1170576
1170578    1170578
1170579    1170579
1170581    1170581
1170583    1170583
1170585    1170585
1170587    1170587
1170588    1170588
1170589    1170589
1170567    1170567
1170541    1170541
1170539    1170539
1170538    1170538
1170493    1170493
...            ...
660255      660255
659581      659581
660253      660253
660244      660244
660181      660181
660185      660185
660186      660186
660188      660188
660189      660189
660190      660190
660191      660191
660193      660193
660194      660194
660195      660195
660197      660197
660198      660198
660208      660208
660212      660212
660213      660213
660217      660217
660223      660223
660224      660224
660225      660225
660231      660231
660235      660235
660237      660237
660238      660238
660240      660240
660243      660243
660248      660248

[929615 rows x 1 columns]

## Train model

In [11]:
x_vars.head()

,ncodpers,canal_entrada,conyuemp,ind_actividad_cliente,ind_empleado,ind_nuevo,indext,indfall,indrel,indrel_1mes,...,ind_hip_fin_ult1,ind_nom_pens_ult1,ind_nomina_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_recibo_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1
0,1063111,1.0,0,1.0,1,0.0,2,2,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1063111,1.0,0,1.0,1,0.0,2,2,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1063273,4.0,0,1.0,1,0.0,2,2,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,1063273,4.0,0,1.0,1,0.0,2,2,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,1063250,4.0,0,1.0,1,0.0,2,2,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [12]:
param = {'objective': 'multi:softprob', 
         'eta': 0.05, 
         'max_depth': 8, 
         'silent': 1, 
         'num_class': len(target_cols),
         'eval_metric': 'mlogloss',
         'min_child_weight': 1,
         'subsample': 0.7,
         'colsample_bytree': 0.7,
         'seed': 0}
num_rounds = 50

dtrain = xgb.DMatrix(x_vars.values[:, 1:], target.values[:, 1])
model = xgb.train(param, dtrain, num_rounds, evals=[(dtrain, 'train')], verbose_eval=True)

[0]	train-mlogloss:2.91487
[1]	train-mlogloss:2.78413
[2]	train-mlogloss:2.65707
[3]	train-mlogloss:2.56627
[4]	train-mlogloss:2.47336
[5]	train-mlogloss:2.39498
[6]	train-mlogloss:2.33034
[7]	train-mlogloss:2.27007
[8]	train-mlogloss:2.21553
[9]	train-mlogloss:2.16426
[10]	train-mlogloss:2.11573
[11]	train-mlogloss:2.07031
[12]	train-mlogloss:2.02763
[13]	train-mlogloss:1.98783
[14]	train-mlogloss:1.95158
[15]	train-mlogloss:1.91729
[16]	train-mlogloss:1.88337
[17]	train-mlogloss:1.85356
[18]	train-mlogloss:1.8235
[19]	train-mlogloss:1.79742
[20]	train-mlogloss:1.7708
[21]	train-mlogloss:1.74593
[22]	train-mlogloss:1.72276
[23]	train-mlogloss:1.70214
[24]	train-mlogloss:1.68208
[25]	train-mlogloss:1.66204
[26]	train-mlogloss:1.64193
[27]	train-mlogloss:1.62316
[28]	train-mlogloss:1.60568
[29]	train-mlogloss:1.58919
[30]	train-mlogloss:1.57423
[31]	train-mlogloss:1.55851
[32]	train-mlogloss:1.54499
[33]	train-mlogloss:1.53018
[34]	train-mlogloss:1.5167
[35]	train-mlogloss:1.50313
[36]	train-mlogloss:1.49054
[37]	train-mlogloss:1.47803
[38]	train-mlogloss:1.46689
[39]	train-mlogloss:1.4562
[40]	train-mlogloss:1.44564
[41]	train-mlogloss:1.43474
[42]	train-mlogloss:1.42467
[43]	train-mlogloss:1.41476
[44]	train-mlogloss:1.40545
[45]	train-mlogloss:1.39664
[46]	train-mlogloss:1.38828
[47]	train-mlogloss:1.3795
[48]	train-mlogloss:1.37089
[49]	train-mlogloss:1.36261

Prediction from my model

In [13]:
preds = model.predict(xgb.DMatrix(x_vars_test.values[:, 1:]))
preds = np.argsort(preds, axis=1)
preds = np.fliplr(preds)[:, :7]

Write out prediction results from my model

In [14]:
test_id = x_vars_test.loc[:, 'ncodpers'].values
final_preds = [' '.join([target_cols[k] for k in pred]) for pred in preds]

out_df = pd.DataFrame({'ncodpers': test_id, 'added_products': final_preds})
out_df.to_csv('eda_4_11.csv.gz', compression='gzip', index=False)

In [15]:
train_X = np.load('train_X.npy')

In [16]:
x_vars.shape

(45679, 41)

In [17]:
train_X.shape

(45679, 40)

In [18]:
u = x_vars.values[:, 1:]

In [19]:
a = u-train_X

In [21]:
np.abs(a).max()

5.000000000000143e-05

In [23]:
train_y = np.load('train_y.npy')
u = target.values[:, 1]

In [24]:
a = train_y-u

In [26]:
np.abs(a).max()

0

In [37]:
test_X = np.load('test_X.npy')
u = x_vars_test.fillna(0.0).values[:, 1:]

In [38]:
a = test_X-u

In [42]:
np.abs(a)

125831.59972158297

In [35]:
test_X

array([[ 5.,  2.,  1., ...,  1.,  1.,  0.],
       [ 5.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  1., ...,  0.,  0.,  0.],
       ...,
       [67.,  0.,  1., ...,  0.,  0.,  0.],
       [ 4.,  0.,  0., ...,  0.,  0.,  0.],
       [ 5.,  0.,  0., ...,  0.,  0.,  0.]])

In [36]:
x_vars_test.isnull().sum()

ncodpers                      0
canal_entrada                 0
conyuemp                      0
ind_actividad_cliente         0
ind_empleado                  0
ind_nuevo                     0
indext                        0
indfall                       0
indrel                        0
indrel_1mes                   0
indresi                       0
pais_residencia               0
segmento                      0
sexo                          0
tipodom                       0
tiprel_1mes                   0
age                           0
antiguedad                    0
renta                         0
ind_cco_fin_ult1         307211
ind_cder_fin_ult1        307211
ind_cno_fin_ult1         307211
ind_ctju_fin_ult1        307211
ind_ctma_fin_ult1        307211
ind_ctop_fin_ult1        307211
ind_ctpp_fin_ult1        307211
ind_deco_fin_ult1        307211
ind_dela_fin_ult1        307211
ind_deme_fin_ult1        307211
ind_ecue_fin_ult1        307211
ind_fond_fin_ult1        307211
ind_hip_fin_ult1         307211
ind_nom_pens_ult1        307211
ind_nomina_ult1          307211
ind_plan_fin_ult1        307211
ind_pres_fin_ult1        307211
ind_reca_fin_ult1        307211
ind_recibo_ult1          307211
ind_tjcr_fin_ult1        307211
ind_valo_fin_ult1        307211
ind_viv_fin_ult1         307211
dtype: int64